"""Export integrated annotations back to their source file formats.

Inverse of the writers in :mod:`voxhub_core.integrate`: reads annotation
zarr arrays and produces 3D Slicer-compatible ``.seg.nrrd`` /
``.mrk.json`` files.  Used by ``prepare-pull`` to populate the
``reference/`` subdirectory of a staging session.

Spatial metadata is read from the store's raw volume (``raw/full``) and
applied to the exported file — the annotation array itself does not
carry space origin / directions.

This module is distinct from :mod:`voxhub_core.export`, which handles
the DICOM → zarr ingestion pipeline.
"""

import hashlib
from pathlib import Path
from typing import Any

import nrrd
import numpy as np
import zarr

from voxhub_core.slicer import write_mrk_json
from voxhub_core.staging import extract_spatial_metadata


class ExportError(Exception):
    """Raised when an annotation cannot be exported.

    Callers (notably ``_run_prepare_pull``) treat ``ExportError`` as
    non-fatal: the offending annotation is skipped and surfaced in
    ``skipped_annotations`` so the annotator is never silently denied a
    reference file they asked for.
    """


def _compute_sha256(path: Path) -> str:
    """Compute ``sha256:<hex>`` of a file."""
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(8192), b''):
            h.update(chunk)
    return f'sha256:{h.hexdigest()}'


def _read_spatial_metadata(
    zarr_path: Path,
) -> tuple[np.ndarray, np.ndarray]:
    """Read ``(origin_lps, space_directions)`` from the store's raw volume."""
    try:
        root = zarr.open_group(zarr_path, mode='r')
        raw_attrs = dict(root['raw']['full'].attrs)
        origin, space_directions, _ = extract_spatial_metadata(raw_attrs)
    except (KeyError, FileNotFoundError) as exc:
        msg = f'failed to read spatial metadata from {zarr_path}: {exc}'
        raise ExportError(msg) from exc
    return origin, space_directions


def _open_annotation_array(zarr_path: Path, array_zarr_path: str) -> zarr.Array:
    """Open an annotation array at ``zarr_path/array_zarr_path``."""
    try:
        root = zarr.open_group(zarr_path, mode='r')
    except FileNotFoundError as exc:
        msg = f'zarr store not found: {zarr_path}'
        raise ExportError(msg) from exc
    try:
        node = root[array_zarr_path]
    except KeyError as exc:
        msg = f'annotation array not found: {array_zarr_path}'
        raise ExportError(msg) from exc
    if not isinstance(node, zarr.Array):
        msg = f'expected a zarr array at {array_zarr_path}, got {type(node).__name__}'
        raise ExportError(msg)
    return node


def _build_seg_nrrd_header(
    origin: np.ndarray,
    space_directions: np.ndarray,
    segments: list[dict[str, Any]],
) -> dict[str, Any]:
    """Build a Slicer-compatible NRRD header for a segmentation export.

    Minimal version of :func:`voxhub_core.slicer.build_seg_nrrd_header`
    — only what Slicer needs to round-trip.  We deliberately skip the
    per-segment ``Extent`` field: pynrrd will compute it from the label
    map itself when needed, and it would otherwise require a second pass
    over a potentially large volume.
    """
    header: dict[str, Any] = {
        'space': 'left-posterior-superior',
        'space origin': origin.tolist(),
        'space directions': space_directions.tolist(),
        'kinds': ['domain', 'domain', 'domain'],
        'Segmentation_ContainedRepresentationNames': 'Binary labelmap',
        'Segmentation_MasterRepresentation': 'Binary labelmap',
        'Segmentation_ReferenceImageExtentOffset': '0 0 0',
    }
    for i, seg in enumerate(segments):
        color = seg['color']
        header[f'Segment{i}_ID'] = str(seg['id'])
        header[f'Segment{i}_Name'] = str(seg['name'])
        header[f'Segment{i}_Color'] = (
            f'{float(color[0])} {float(color[1])} {float(color[2])}'
        )
        header[f'Segment{i}_LabelValue'] = str(int(seg['label_value']))
        header[f'Segment{i}_Layer'] = '0'
        header[f'Segment{i}_NameAutoGenerated'] = '0'
    return header


def export_segmentation(
    zarr_path: Path,
    array_zarr_path: str,
    dest: Path,
) -> str:
    """Export an integrated segmentation zarr array to a ``.seg.nrrd`` file.

    Parameters
    ----------
    zarr_path : Path
        Path to the source ``.zarr`` store.
    array_zarr_path : str
        Path of the annotation array within the zarr hierarchy, e.g.
        ``'annotations/alice-xyz45678/inner-ear-structures-20260101-ab12/data'``.
    dest : Path
        Destination file path for the exported ``.seg.nrrd``.

    Returns
    -------
    str
        ``sha256:<hex>`` digest of the written file.

    Raises
    ------
    ExportError
        If the array is missing, has an unsupported dtype, or lacks the
        ``segments`` attribute.
    """
    origin, space_directions = _read_spatial_metadata(zarr_path)
    arr = _open_annotation_array(zarr_path, array_zarr_path)

    try:
        label_map = np.asarray(arr[:])
    except Exception as exc:  # pragma: no cover — defensive
        msg = f'failed to read label map from {array_zarr_path}: {exc}'
        raise ExportError(msg) from exc

    if label_map.ndim != 3:
        msg = (
            f'segmentation label map at {array_zarr_path} must be '
            f'3-dimensional, got ndim={label_map.ndim}'
        )
        raise ExportError(msg)
    if not np.issubdtype(label_map.dtype, np.integer):
        msg = (
            f'segmentation label map at {array_zarr_path} must have integer '
            f'dtype, got {label_map.dtype}'
        )
        raise ExportError(msg)

    ann_attrs = dict(arr.attrs)
    segments_raw = ann_attrs.get('segments')
    if not isinstance(segments_raw, list):
        msg = (
            f"annotation at {array_zarr_path} is missing a 'segments' "
            f'attribute (is it really a segmentation?)'
        )
        raise ExportError(msg)

    segments: list[dict[str, Any]] = []
    for i, raw in enumerate(segments_raw):
        if not isinstance(raw, dict):
            msg = (
                f'annotation at {array_zarr_path}: segments[{i}] is not a '
                f'dict, got {type(raw).__name__}'
            )
            raise ExportError(msg)
        missing = {'id', 'name', 'label_value', 'color'} - set(raw.keys())
        if missing:
            msg = (
                f'annotation at {array_zarr_path}: segments[{i}] missing '
                f'keys {sorted(missing)!r}'
            )
            raise ExportError(msg)
        segments.append(dict(raw))

    header = _build_seg_nrrd_header(origin, space_directions, segments)

    dest.parent.mkdir(parents=True, exist_ok=True)
    try:
        nrrd.write(str(dest), label_map, header)
    except Exception as exc:
        msg = f'failed to write {dest}: {exc}'
        raise ExportError(msg) from exc

    return _compute_sha256(dest)


def export_landmarks(
    zarr_path: Path,
    array_zarr_path: str,
    dest: Path,
) -> str:
    """Export an integrated landmark zarr array to a ``.mrk.json`` file.

    The points are already stored in LPS (the integrate path converts
    RAS inputs on write), so the exported file declares
    ``coordinateSystem: 'LPS'``.

    Parameters
    ----------
    zarr_path : Path
        Path to the source ``.zarr`` store.  Opened only to resolve the
        annotation array; landmark export does not consume spatial
        metadata from the raw volume.
    array_zarr_path : str
        Path of the annotation array within the zarr hierarchy.
    dest : Path
        Destination file path for the exported ``.mrk.json``.

    Returns
    -------
    str
        ``sha256:<hex>`` digest of the written file.

    Raises
    ------
    ExportError
        If the array is missing, has an unexpected shape, or lacks the
        ``labels`` attribute.
    """
    arr = _open_annotation_array(zarr_path, array_zarr_path)

    try:
        points = np.asarray(arr[:], dtype=np.float64)
    except Exception as exc:  # pragma: no cover — defensive
        msg = f'failed to read landmark points from {array_zarr_path}: {exc}'
        raise ExportError(msg) from exc

    if points.ndim != 2 or points.shape[1] != 3:
        msg = (
            f'landmark points at {array_zarr_path} must have shape (N, 3), '
            f'got {points.shape}'
        )
        raise ExportError(msg)

    ann_attrs = dict(arr.attrs)
    labels_raw = ann_attrs.get('labels')
    if not isinstance(labels_raw, list):
        msg = (
            f"annotation at {array_zarr_path} is missing a 'labels' "
            f'attribute (is it really a landmark set?)'
        )
        raise ExportError(msg)
    if len(labels_raw) != points.shape[0]:
        msg = (
            f'annotation at {array_zarr_path}: labels count '
            f'({len(labels_raw)}) does not match points count '
            f'({points.shape[0]})'
        )
        raise ExportError(msg)

    labels: list[str] = []
    for i, lab in enumerate(labels_raw):
        if not isinstance(lab, str):
            msg = (
                f'annotation at {array_zarr_path}: labels[{i}] is not a '
                f'string, got {type(lab).__name__}'
            )
            raise ExportError(msg)
        labels.append(lab)

    dest.parent.mkdir(parents=True, exist_ok=True)
    try:
        write_mrk_json(dest, points, labels, coordinate_system='LPS')
    except Exception as exc:
        msg = f'failed to write {dest}: {exc}'
        raise ExportError(msg) from exc

    return _compute_sha256(dest)
